name: Release

on:
  push:
    branches:
      - master
      
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build Gradle project
        run: gradle assemble

      - name: Archive distribution artifacts
        run: gradle distTar distZip

      - name: Upload distribution artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: build/distributions
